### ISSUE TITLE
Friend Create v1.0.0 Project properties bug

### ISSUE THREAD

**Issue by m6502** [FriendUPCloud/friendup#62] opened 2018-06-07 16:10 UTC
- Open Friend Create v1.0.0
- Click on Project Properties
- Double click on "Module system" or "Module files"
- The double clicked item disappears and nothing else seems to happen.

![project properties](https://user-images.githubusercontent.com/1667712/41112038-1745b57a-6a7e-11e8-8bb6-a6716e9cc730.png)

**Comment by arturlangner** [comment] 2018-08-03 08:11
Thank you - bug confirmed. Internal reference BG-541.

**Comment by titlestad** [comment] 2018-08-17 11:13
This is actually just because it was a lazy implementation :-) But it will be fixed in the next update of Friend Create.

**Comment by titlestad** [comment] 2021-02-13 14:50
This one is now fixed.

**Closed by titlestad** 2021-02-13 14:50 UTC

**Comment by m6502** [comment] 2021-02-13 15:23
👍
